name: SuiMove

permissions:
  contents: read
  pull-requests: write

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    paths:
      - '**.move'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mysten/sui-tools:ci

    steps:
      - uses: actions/checkout@v6

      - name: run Sui Move test
        run: |
          for name in */Move.toml; do
            echo testing $(dirname $name)
            cd $(dirname $name) && sui move test && cd .. || exit 1
          done

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # @v2
      - uses: oven-sh/setup-bun@22457c87c1b161cf7dde222c3e82b2b5f8d2bed2
      - run: bun install @mysten/prettier-plugin-move

      - run: bun prettier-move --config .prettier-move.json -c **/*.move
